version: '3.1'
services:
  db:
    image: postgres:9.6.1
    restart: always
    environment:
      POSTGRES_PASSWORD: informatica
      POSTGRES_DB: movies2
    networks:
      - webnet
  web:
    image: "payara-demo:2019-04-11"
    restart: always
    environment:
      JDBC_URL: 'jdbc:postgresql://db:5432/movies2'
      JAVA_TOOL_OPTIONS: '-Xmx64m'
    ports:
      - 8080
    networks:
      - webnet
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "4000:4000"
    networks:
      - webnet
networks:
  webnet: